online_shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('shop/',include('shop.urls',namespace='shop')),
    path('',include('shop.urls',namespace='shop')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views


app_name='shop'

urlpatterns=[
    path('', views.UserHomeView.as_view(), name='home'),
    path('workshop/', views.ProductView.as_view(), name='workshop'),
    path('product_details/<slug:slug>', views.ProductDetailView.as_view(), name='details'),
    path('cart/',views.CartView.as_view(),name='cart'),
    path('add_cart/<int:product_id>/',views.CartAddView.as_view(),name='add_cart'),
    path('remove_cart/<str:product_id>/',views.CartRemoveView.as_view(),name='remove_cart'),
    path('order_create/',views.OrderCreateView.as_view(),name='order_create'),
    path('order_detail/<int:order_id>/',views.OrderDetailView.as_view(),name='order_detail'),
    path('apply_coupon/<int:order_id>/',views.CouponPriceView.as_view(),name='apply_coupon'),
    path('final_price/<int:order_id>/',views.FinalPriceView.as_view(),name='final_price'),
]

shop/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator,MaxValueValidator



class Category(models.Model):
    name=models.CharField(max_length=100)
    slug=models.SlugField()

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    name=models.CharField(max_length=100)
    slug=models.SlugField(unique=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE,related_name='category_name')
    image=models.ImageField(upload_to='products/')
    price=models.IntegerField()
    description=models.TextField()
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    available=models.BooleanField(default=True)

    class Meta:
        ordering=('name',)


    def __str__(self):
        return f"{self.name}-{self.price}-{self.available}"


class Order(models.Model):
    user=models.ForeignKey(get_user_model(),on_delete=models.CASCADE,related_name='orders')
    paid=models.BooleanField(default=False)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    discount=models.IntegerField(null=True,blank=True,default=None)

    def get_total_price(self):
        total_price=sum(item.get_cost() for item in self.items.all())
        if self.discount:
            discount_price=(self.discount/100)*total_price
            return (total_price-discount_price)
        return total_price

    class Meta:
        ordering=('paid',)

    def __str__(self):
        return self.user


class OrderItem(models.Model):
    order=models.ForeignKey(Order,on_delete=models.CASCADE,related_name='items')
    product=models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    price=models.IntegerField()


    def __str__(self):
        return f"{self.order}"

    def get_cost(self):
        return self.quantity * self.price


class Coupon(models.Model):
    code=models.CharField(max_length=30,unique=True)
    valid_from=models.DateTimeField()
    valid_to=models.DateTimeField()
    active=models.BooleanField()
    discount=models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(90)])

    def __str__(self):
        return self.code

shop/forms.py
from django import forms


class CartAddForm(forms.Form):
    quantity=forms.IntegerField(label='تعداد',min_value=1,max_value=10)


class CouponForm(forms.Form):
    code=forms.CharField(max_length=30)

shop/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views import View
from .models import Product,Category,Order,OrderItem,Coupon
from .cart import Cart
from .forms import CartAddForm,CouponForm
from django.contrib.auth.mixins import LoginRequiredMixin
from datetime import datetime
from django.contrib import messages
import pytz


class UserHomeView(View):
    def get(self,request):
         product=Product.objects.all()
         return render(request,'shop/index.html',{'products':product})


class ProductView(View):
    def get(self,request):
        return render(request,'shop/wokshop.html')


class ProductDetailView(View):
    class_form=CartAddForm
    def get(self,request,slug):
        product=get_object_or_404(Product,slug=slug)
        return render(request,'shop/product_details.html',{'product':product,'form':self.class_form})


class CartView(View):

    def get(self,request):
        cart=Cart(request)
        total_price=cart.get_total_price()
        return render(request,'shop/cart.html',{'cart':cart,'total_price':total_price})

    def post(self,request):
        pass


class CartAddView(View):

    def post(self,request,product_id):
        cart=Cart(request)
        product=get_object_or_404(Product,id=product_id)
        form=CartAddForm(request.POST)
        if form.is_valid():
            cart.add(product,form.cleaned_data['quantity'])
        return redirect('shop:cart')


class CartRemoveView(View):
    def get(self,request,product_id):
        cart=Cart(request)
        product=get_object_or_404(Product,id=int(product_id))
        cart.remove(product)
        return redirect('shop:cart')

class OrderCreateView(LoginRequiredMixin, View):
    def get(self,request):
        cart=Cart(request)
        order=Order.objects.create(user=request.user)
        for item in cart:
            product=get_object_or_404(Product,id=int(item['id']))
            OrderItem.objects.create(order=order,product=product,quantity=item['quantity'],price=item['price'])
        cart.clear()
        return redirect('shop:order_detail',order.id)


class OrderDetailView(LoginRequiredMixin,View):
    form_class=CouponForm
    def get(self,request,order_id):
        order=get_object_or_404(Order,id=order_id)
        return render(request,'shop/order_detail.html',{'order':order,'form':self.form_class})
    def post(self):
        pass

class CouponPriceView(LoginRequiredMixin,View):
    form_class=CouponForm
    def post(self,request,order_id):
        form=self.form_class(request.POST)
        now=datetime.now(tz=pytz.timezone('Asia/Tehran'))
        print('here===============')
        if form.is_valid():
            cd_code=form.cleaned_data['code']
            print(cd_code)
            try:
                 coupon_validation=Coupon.objects.get(code__exact=cd_code,valid_from__lte=now,valid_to__gte=now,active=True)
                 print(coupon_validation)
            except Coupon.DoesNotExist:
                 messages.error(request,'Coupon dose not exists','error')
                 return redirect('shop:order_detail',order_id)
            order=Order.objects.get(id=order_id)
            order.discount=coupon_validation.discount
            order.save()
        return redirect('shop:final_price',order_id)

class FinalPriceView(LoginRequiredMixin,View):
    def get(self,request,order_id):
        order=Order.objects.get(id=order_id)
        return render(request,'shop/final_price.html',{'order':order})

shop/templates/shop/cart.html
{% extends 'base.html' %}

{% block content %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">شماره</th>
            <th scope="col">نام کالا</th>
            <th scope="col">تعداد</th>
            <th scope="col">قیمت واحد</th>
            <th scope="col">جمع کل</th>
        </tr>
        </thead>
        <tbody>

        {% for item in cart %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ item.product }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.price }}</td>
                <td>{{ item.total_price }}</td>
                <td><a href="{% url 'shop:remove_cart' item.id %}" style="text-decoration: none;">حذف</a></td>

            </tr>

        {% endfor %}
        <tr>
            <td colspan="4" style="background-color: darkkhaki;">پرداخت نهایی</td>
            <td style="background-color: chocolate;">{{ total_price }}</td>
        </tr>
        </tbody>
    </table>
{#    <input type="button" class="btn btn-success" href="{% url 'shop:order_create' %}" value="پرداخت">#}
    <a class="btn btn-success" href="{% url 'shop:order_create' %}">پرداخت</a>
{% endblock %}

shop/templates/shop/final_price.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">شماره سفارش</th>
            <th scope="col">مبلغ</th>
            <th scope="col">نام مشتری</th>
            <th scope="col">وضعیت پرداخت</th>

        </tr>
        </thead>
        <tbody>

        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order.get_total_price }}</td>
            <td>{{ order.user }}</td>
            {% if order.paid %}
                <td><img src="{% static 'shop/img/tick1.jpg' %}"></td>
            {% else %}
                <td><img src="{% static 'shop/img/fault tick1.png' %}"></td>
            {% endif %}

        </tr>


        </tbody>
    </table>
    <input type="button" class="btn btn-success" value="پرداخت">

{% endblock %}

shop/templates/shop/index.html
{% extends 'base.html' %}
{% load static %}
{% block css_code %}
    <link rel="stylesheet" href="{% static 'shop/css/product_page.css' %}">
{% endblock %}
{% block content %}
    {% for product in products %}
        <div style="display: inline-block;margin-left: 30px;margin-right: 30px;">
            <div class="card-group" style="width: 18rem;">
                <div class="card">
                    <img class="card-img-top " src="{{ product.image.url }}" alt="{{ product.slug}}">
                    <div class="card-body">
                        <a href="{% url 'shop:details' product.slug %}" > <h5 class="card-title">{{ product.name}}</h5></a>
                        <p class="card-text"><small class="text-muted">Last updated {{ product.updated|timesince }} mins ago</small></p>
                    </div>
                </div>
            </div>
        </div>

    {% endfor %}
{% endblock %}

shop/templates/shop/order_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
   <table class="table">
        <thead>
        <tr>
            <th scope="col">شماره سفارش</th>
            <th scope="col">نام مشتری</th>
            <th scope="col">وضعیت پرداخت</th>

        </tr>
        </thead>
        <tbody>

            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ order.user }}</td>
                {% if order.paid %}
                 <td><img src="{% static 'shop/img/tick1.jpg' %}"></td>
                {% else %}
                   <td><img src="{% static 'shop/img/fault tick1.png' %}"></td>
                {% endif %}

            </tr>



        </tbody>
    </table>
    <input type="button" class="btn btn-success" value="پرداخت">

{% endblock %}

shop/templates/shop/product_details.html
{% extends 'base.html' %}
{% load static %}
{% block css_code %}
    <link href="{% static 'shop/css/product_detail.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}
    <div class="contianer">

        <div class="right_position">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="{{ product.image.url }}" alt="Card image cap">
                <div class="card-body">
                    <p class="card-text"></p>
                </div>
            </div>

        </div>

        <div class="center_position">
            <h2>
                {{ product.name }}
            </h2>
            <br>
            <p class="card-text"><small class="text-muted">Last updated {{ product.updated|timesince }} mins ago</small>
            </p>
            <br>
            <form action="{% url 'shop:add_cart' product.id %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
                {% if product.available %}
                    <input type="submit" class="btn btn-success btn-lg" value="اضافه کردن به سبد خرید">
                {% else %}
                    <input type="submit" class="btn btn-warning disabled" value="ناموجود">
                {% endif %}
            </form>

        </div>

        <div class="left_position">
            <p>
                {{ product.description }}
            </p>
        </div>
    </div>

{% endblock %}

shop/templates/shop/wokshop.html
{% extends 'base.html' %}


{% block content %}
  <div class="card-deck">
  <div class="card">
    <img class="card-img-top" src="..." alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
  <div class="card">
    <img class="card-img-top" src="..." alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
  <div class="card">
    <img class="card-img-top" src="..." alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
</div>

{% endblock %}