accounts/urls.py
from django.urls import path
from . import views


app_name='accounts'

urlpatterns=[
    path('login/',views.UserLoginView.as_view(),name='login'),
    path('logout/',views.UserLogoutView.as_view(),name='logout'),
    path('register/',views.UserRegisterView.as_view(),name='register'),
    path('verify/',views.UserVerifyCodeView.as_view(),name='verify'),
]

online_shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('shop/',include('shop.urls',namespace='shop')),
    path('',include('shop.urls',namespace='shop')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views


app_name='shop'

urlpatterns=[
    path('', views.UserHomeView.as_view(), name='home'),
    path('workshop/', views.ProductView.as_view(), name='workshop'),
    path('product_details/<slug:slug>', views.ProductDetailView.as_view(), name='details'),
    path('cart/',views.CartView.as_view(),name='cart'),
    path('add_cart/<int:product_id>/',views.CartAddView.as_view(),name='add_cart'),
    path('remove_cart/<str:product_id>/',views.CartRemoveView.as_view(),name='remove_cart'),
    path('order_create/',views.OrderCreateView.as_view(),name='order_create'),
    path('order_detail/<int:order_id>/',views.OrderDetailView.as_view(),name='order_detail'),
    path('apply_coupon/<int:order_id>/',views.CouponPriceView.as_view(),name='apply_coupon'),
    path('final_price/<int:order_id>/',views.FinalPriceView.as_view(),name='final_price'),
]

templates/inc/message.html
{% if messages %}
{% for msg in messages %}
    <p class="alert alert-{{ msg.tags }} text-center" style="font-family: 'B Yekan'">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg bg-light" style="font-family:'B Yekan';">

    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link " aria-current="page" href="{% url 'shop:home' %}">صفحه نخست</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'shop:cart' %}">  سبد خرید{{ cart_num|length }}  </a>
        </li>

        {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">خروج</a>
            </li>

        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">ورود</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:register' %}">ثبت نام</a>
            </li>
        {% endif %}

    </ul>

</nav>